In [1]:
import nltk

In [5]:
# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

In [6]:
nltk.download('popular')

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular

True

In [7]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [8]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [9]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [10]:
pwd

'C:\\Users\\Fathima'

In [11]:
cd downloads

C:\Users\Fathima\downloads

In [12]:
cd Spotify NLP

C:\Users\Fathima\downloads\Spotify NLP

In [13]:
import pandas as pd
df = pd.read_csv("Spotify App Reviews.csv")
df

,Time_submitted,Review,Rating,Total_thumbsup,Reply
0,2022-07-09 15:00:00,"Great music service, the audio is high quality...",5,2,NaN
1,2022-07-09 14:21:22,Please ignore previous negative rating. This a...,5,1,NaN
2,2022-07-09 13:27:32,"This pop-up ""Get the best Spotify experience o...",4,0,NaN
3,2022-07-09 13:26:45,Really buggy and terrible to use as of recently,1,1,NaN
4,2022-07-09 13:20:49,Dear Spotify why do I get songs that I didn't ...,1,1,NaN
...,...,...,...,...,...
61589,2022-01-01 03:01:29,Even though it was communicated that lyrics fe...,1,6,NaN
61590,2022-01-01 02:13:40,"Use to be sooo good back when I had it, and wh...",1,0,NaN
61591,2022-01-01 01:02:29,This app would be good if not for it taking ov...,2,10,NaN
61592,2022-01-01 00:49:23,The app is good hard to navigate and won't jus...,2,1,NaN
61593,2022-01-01 00:19:09,Its good but sometimes it doesnt load the musi...,4,0,NaN

In [14]:
df.head()

,Time_submitted,Review,Rating,Total_thumbsup,Reply
0,2022-07-09 15:00:00,"Great music service, the audio is high quality...",5,2,NaN
1,2022-07-09 14:21:22,Please ignore previous negative rating. This a...,5,1,NaN
2,2022-07-09 13:27:32,"This pop-up ""Get the best Spotify experience o...",4,0,NaN
3,2022-07-09 13:26:45,Really buggy and terrible to use as of recently,1,1,NaN
4,2022-07-09 13:20:49,Dear Spotify why do I get songs that I didn't ...,1,1,NaN

In [15]:
df.info

<bound method DataFrame.info of             Time_submitted                                             Review  \
0      2022-07-09 15:00:00  Great music service, the audio is high quality...
1      2022-07-09 14:21:22  Please ignore previous negative rating. This a...
2      2022-07-09 13:27:32  This pop-up "Get the best Spotify experience o...
3      2022-07-09 13:26:45    Really buggy and terrible to use as of recently
4      2022-07-09 13:20:49  Dear Spotify why do I get songs that I didn't ...
...                    ...                                                ...
61589  2022-01-01 03:01:29  Even though it was communicated that lyrics fe...
61590  2022-01-01 02:13:40  Use to be sooo good back when I had it, and wh...
61591  2022-01-01 01:02:29  This app would be good if not for it taking ov...
61592  2022-01-01 00:49:23  The app is good hard to navigate and won't jus...
61593  2022-01-01 00:19:09  Its good but sometimes it doesnt load the musi...

       Rating  Total_thumbsup Reply
0           5               2   NaN
1           5               1   NaN
2           4               0   NaN
3           1               1   NaN
4           1               1   NaN
...       ...             ...   ...
61589       1               6   NaN
61590       1               0   NaN
61591       2              10   NaN
61592       2               1   NaN
61593       4               0   NaN

[61594 rows x 5 columns]>

In [16]:
df.columns

Index(['Time_submitted', 'Review', 'Rating', 'Total_thumbsup', 'Reply'], dtype='object')

In [17]:
# Selecting review text and target column
text_column = 'Review'
target_column = 'Rating'
df1 = df[[text_column, target_column]].dropna()
df1.head()

                                              Review  Rating
0  Great music service, the audio is high quality...       5
1  Please ignore previous negative rating. This a...       5
2  This pop-up "Get the best Spotify experience o...       4
3    Really buggy and terrible to use as of recently       1
4  Dear Spotify why do I get songs that I didn't ...       1

In [18]:
# Text Cleaning
import re
def clean(text):
    text = re.sub('[^A-Za-z]+', ' ', str(text))
    return text
df1['Cleaned Text'] = df1[text_column].apply(clean)
df1.head()

,Review,Rating,Cleaned Text
0,"Great music service, the audio is high quality...",5,Great music service the audio is high quality ...
1,Please ignore previous negative rating. This a...,5,Please ignore previous negative rating This ap...
2,"This pop-up ""Get the best Spotify experience o...",4,This pop up Get the best Spotify experience on...
3,Really buggy and terrible to use as of recently,1,Really buggy and terrible to use as of recently
4,Dear Spotify why do I get songs that I didn't ...,1,Dear Spotify why do I get songs that I didn t ...

In [19]:
# Lowercase
df1['Lowercase'] = df1['Cleaned Text'].apply(lambda x: " ".join(word.lower() for word in x.split()))
df1.head()

,Review,Rating,Cleaned Text,Lowercase
0,"Great music service, the audio is high quality...",5,Great music service the audio is high quality ...,great music service the audio is high quality ...
1,Please ignore previous negative rating. This a...,5,Please ignore previous negative rating This ap...,please ignore previous negative rating this ap...
2,"This pop-up ""Get the best Spotify experience o...",4,This pop up Get the best Spotify experience on...,this pop up get the best spotify experience on...
3,Really buggy and terrible to use as of recently,1,Really buggy and terrible to use as of recently,really buggy and terrible to use as of recently
4,Dear Spotify why do I get songs that I didn't ...,1,Dear Spotify why do I get songs that I didn t ...,dear spotify why do i get songs that i didn t ...

In [20]:
# Stopwords Removal
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
df1['stopwords'] = df1['Lowercase'].apply(
    lambda x: " ".join(word for word in x.split() if word not in stop_words))
df1.head()

,Review,Rating,Cleaned Text,Lowercase,stopwords
0,"Great music service, the audio is high quality...",5,Great music service the audio is high quality ...,great music service the audio is high quality ...,great music service audio high quality app eas...
1,Please ignore previous negative rating. This a...,5,Please ignore previous negative rating This ap...,please ignore previous negative rating this ap...,please ignore previous negative rating app sup...
2,"This pop-up ""Get the best Spotify experience o...",4,This pop up Get the best Spotify experience on...,this pop up get the best spotify experience on...,pop get best spotify experience android annoyi...
3,Really buggy and terrible to use as of recently,1,Really buggy and terrible to use as of recently,really buggy and terrible to use as of recently,really buggy terrible use recently
4,Dear Spotify why do I get songs that I didn't ...,1,Dear Spotify why do I get songs that I didn t ...,dear spotify why do i get songs that i didn t ...,dear spotify get songs put playlist shuffle play

In [21]:
# Tokenization and POS Tagging
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet
from nltk import pos_tag
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Fathima\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [22]:
# POS Conversion
def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return None

df1['POS tagged'] = df1['stopwords'].apply(
    lambda x: pos_tag(word_tokenize(x)))
df1['Wordnet_POS'] = df1['POS tagged'].apply(
    lambda x: [(word, get_wordnet_pos(pos)) for (word, pos) in x])
df1.head()

,Review,Rating,Cleaned Text,Lowercase,stopwords,POS tagged,Wordnet_POS
0,"Great music service, the audio is high quality...",5,Great music service the audio is high quality ...,great music service the audio is high quality ...,great music service audio high quality app eas...,"[(great, JJ), (music, NN), (service, NN), (aud...","[(great, a), (music, n), (service, n), (audio,..."
1,Please ignore previous negative rating. This a...,5,Please ignore previous negative rating This ap...,please ignore previous negative rating this ap...,please ignore previous negative rating app sup...,"[(please, VB), (ignore, RB), (previous, JJ), (...","[(please, v), (ignore, r), (previous, a), (neg..."
2,"This pop-up ""Get the best Spotify experience o...",4,This pop up Get the best Spotify experience on...,this pop up get the best spotify experience on...,pop get best spotify experience android annoyi...,"[(pop, NN), (get, NN), (best, JJS), (spotify, ...","[(pop, n), (get, n), (best, a), (spotify, n), ..."
3,Really buggy and terrible to use as of recently,1,Really buggy and terrible to use as of recently,really buggy and terrible to use as of recently,really buggy terrible use recently,"[(really, RB), (buggy, JJ), (terrible, JJ), (u...","[(really, r), (buggy, a), (terrible, a), (use,..."
4,Dear Spotify why do I get songs that I didn't ...,1,Dear Spotify why do I get songs that I didn t ...,dear spotify why do i get songs that i didn t ...,dear spotify get songs put playlist shuffle play,"[(dear, JJ), (spotify, NN), (get, VBP), (songs...","[(dear, a), (spotify, n), (get, v), (songs, n)..."

In [23]:
# Lemmatization
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()
def lemmatize(pos_data):
    ans = " "
    for word, pos in pos_data:
        if not pos:
            lemma = word
        else:
            lemma = wordnet_lemmatizer.lemmatize(word, pos=pos)
        ans += lemma + " "
    return ans
df1['Lemma'] = df1['Wordnet_POS'].apply(lemmatize)

df1.head()

,Review,Rating,Cleaned Text,Lowercase,stopwords,POS tagged,Wordnet_POS,Lemma
0,"Great music service, the audio is high quality...",5,Great music service the audio is high quality ...,great music service the audio is high quality ...,great music service audio high quality app eas...,"[(great, JJ), (music, NN), (service, NN), (aud...","[(great, a), (music, n), (service, n), (audio,...",great music service audio high quality app ea...
1,Please ignore previous negative rating. This a...,5,Please ignore previous negative rating This ap...,please ignore previous negative rating this ap...,please ignore previous negative rating app sup...,"[(please, VB), (ignore, RB), (previous, JJ), (...","[(please, v), (ignore, r), (previous, a), (neg...",please ignore previous negative rating app su...
2,"This pop-up ""Get the best Spotify experience o...",4,This pop up Get the best Spotify experience on...,this pop up get the best spotify experience on...,pop get best spotify experience android annoyi...,"[(pop, NN), (get, NN), (best, JJS), (spotify, ...","[(pop, n), (get, n), (best, a), (spotify, n), ...",pop get best spotify experience android annoy...
3,Really buggy and terrible to use as of recently,1,Really buggy and terrible to use as of recently,really buggy and terrible to use as of recently,really buggy terrible use recently,"[(really, RB), (buggy, JJ), (terrible, JJ), (u...","[(really, r), (buggy, a), (terrible, a), (use,...",really buggy terrible use recently
4,Dear Spotify why do I get songs that I didn't ...,1,Dear Spotify why do I get songs that I didn t ...,dear spotify why do i get songs that i didn t ...,dear spotify get songs put playlist shuffle play,"[(dear, JJ), (spotify, NN), (get, VBP), (songs...","[(dear, a), (spotify, n), (get, v), (songs, n)...",dear spotify get song put playlist shuffle play

In [24]:
# Features and Target
X = df1['Lemma']
y = df1[target_column]

In [25]:
# Train Test Split
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
# TF-IDF Vectorization
tfidf = TfidfVectorizer()
X_train_vec = tfidf.fit_transform(X_train)
X_test_vec = tfidf.transform(X_test)

In [27]:
# Naive Bayes Model
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
model = MultinomialNB()
model.fit(X_train_vec, y_train)
y_pred = model.predict(X_test_vec)
print("Accuracy :", accuracy_score(y_test, y_pred))

Accuracy : 0.5900641285818654

In [29]:
# SVM Model
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
model = LinearSVC()
model.fit(X_train_vec, y_train)
y_pred = model.predict(X_test_vec)
print("Accuracy :", accuracy_score(y_test, y_pred))

Accuracy : 0.6009416348729605

In [28]:
# Classification Report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.49      0.92      0.64      3524
           2       0.00      0.00      0.00      1385
           3       0.00      0.00      0.00      1412
           4       0.45      0.02      0.03      1532
           5       0.70      0.89      0.79      4466

    accuracy                           0.59     12319
   macro avg       0.33      0.37      0.29     12319
weighted avg       0.45      0.59      0.47     12319